server:
  port: 16003

spring:
  datasource:
    url: jdbc:postgresql://10.30.21.124:5432/erms_v10
    username: dev
    password: Ab123456
    driver-class-name: org.postgresql.Driver

  redis:
    host: localhost
    port: 6379

  output:
    ansi:
      enabled: detect
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        generate_statistics: false
        format_sql: false
        type: trace
        show_sql: false
  jackson:
    time-zone: Asia/Saigon
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method       # sắp xếp theo HTTP method
    tagsSorter: alpha              # sắp xếp theo tên tag
    display-request-duration: true
    tryItOutEnabled: true          # bật Try it out mặc định
    doc-expansion: none

login:
  cons-otp-faulty-block: 1800
  need-two-step: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  file:
    name: /home/mk/erms.v10/server-admin.log

minio:
  access:
    name: 5PfJfdPpv9492wCFGXf6
    secret: Sl1STEhdPdgR5sviIuPKYq3PeftoTOlNTSEf2U2q
  url: http://localhost:9000
  bucket-public: detention-center-public
  bucket-public-policy: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "AWS": [
                "*"
            ]
          },
          "Action": [
            "s3:GetBucketLocation",
            "s3:ListBucket"
          ],
          "Resource": [
            "arn:aws:s3:::detention-center-public"
          ]
        },
        {
          "Effect": "Allow",
          "Principal": {
            "AWS": [
                "*"
            ]
          },
          "Action": [
            "s3:GetObject"
          ],
          "Resource": [
            "arn:aws:s3:::detention-center-public/*"
          ]
        }
      ]
    }
  bucket-private: detention-center-private



