create table audit_log
(
    id                  bigint generated by default as identity
        primary key,
    date_created        timestamp,
    event_name          varchar(255),
    message             varchar(255),
    new_value           varchar(1000),
    old_value           varchar(1000),
    persisted_object_id varchar(255),
    provider_code       varchar(255),
    table_name          varchar(255),
    user_id             integer,
    status              varchar(50)
);

alter table audit_log
    owner to dev1;

create table sys_permission
(
    id            serial
        constraint "SYS_PERMISSION_PK"
            primary key,
    tag           varchar(50) not null,
    type          varchar(10),
    method        varchar(10),
    pattern       varchar(128),
    is_white_list smallint,
    create_time   date,
    update_time   date
);

alter table sys_permission
    owner to dev1;

create table sys_role
(
    id             serial
        constraint "SYS_ROLE_PK"
            primary key,
    role_name      varchar(20) not null,
    description    varchar(50),
    sortno         smallint,
    create_user_id integer,
    create_time    date,
    update_time    date,
    removable      smallint
);

alter table sys_role
    owner to dev1;

create table sys_role_permission
(
    id          serial
        constraint "SYS_ROLE_PERMISSION_PK"
            primary key,
    role_id     integer,
    tag         varchar(50),
    create_time date,
    removable   smallint
);

alter table sys_role_permission
    owner to dev1;

create table sys_user
(
    id                serial
        constraint "SYS_USER_PK"
            primary key,
    user_name         varchar(25),
    real_name         varchar(50),
    description       varchar(50),
    password          varchar(64),
    secret            varchar(64),
    two_step          integer,
    last_login        timestamp(6),
    last_faulty_login timestamp(6),
    cons_otp_faulty   integer,
    cons_pass_faulty  integer,
    create_time       timestamp,
    update_time       timestamp,
    create_user       integer,
    update_user       integer,
    removable         smallint,
    mail              varchar(50),
    phone_number      varchar(12),
    unit_id           integer,
    provider_code     varchar(50)
);

alter table sys_user
    owner to dev1;

create table sys_user_role
(
    id          serial
        constraint "SYS_USER_ROLE_PK"
            primary key,
    user_id     integer not null,
    role_id     integer not null,
    create_time date,
    removable   integer
);

alter table sys_user_role
    owner to dev1;

create table unit
(
    id               serial
        constraint unit_pk
            primary key,
    unit_code        varchar(25),
    unit_name        varchar(50),
    address          varchar(200),
    create_time      date,
    create_user      integer,
    update_user      integer,
    parent_unit_code varchar(25),
    update_time      date
);

alter table unit
    owner to dev1;

create table detainee
(
    id                 serial,
    doc_type           integer,
    id_number          varchar(15),
    full_name          varchar(100),
    sex                integer,
    date_of_birth      date,
    place_of_residence varchar(200),
    place_of_origin    varchar(200),
    nationality_code   varchar(5),
    father_name        varchar(150),
    mother_name        varchar(150),
    ethnic             varchar(150),
    spouse_name        varchar(150),
    other_name         varchar(150),
    create_time        date,
    create_user        integer,
    update_time        date,
    update_user        integer
);

alter table detainee
    owner to dev1;

create table fingerprint_carding
(
    id                                           serial
        constraint fingerprint_carding_pk
            primary key,
    no                                           integer,
    date_of_creation                             integer,
    address                                      varchar(255),
    fingerprint_pattern                          varchar(150),
    tw                                           varchar(150),
    place_of_temporary_residence                 varchar(200),
    place_of_current_residence                   varchar(200),
    incident                                     varchar(500),
    officer_in_charge_fingerprint_carding        varchar(150),
    officer_in_charge_sort                       varchar(150),
    officer_in_charge_classification             varchar(150),
    technical_officer_fingerprint_classification varchar(150),
    create_user                                  integer,
    id_number                                    varchar(15),
    create_date                                  date,
    update_date                                  date,
    update_user                                  integer
);

alter table fingerprint_carding
    owner to dev1;

create table country
(
    id              serial
        constraint country_pk
            primary key,
    country_name    varchar(100),
    alpha_2_code    varchar(2),
    alpha_3_code    varchar(3),
    "numeric_code" varchar(5)
);

alter table country
    owner to dev1;

create table criminal_id_record
(
    id                               serial
        constraint criminal_id_record_pk
            primary key,
    id_number                        varchar(15),
    no                               varchar(25),
    date_of_creation                 date,
    address                          varchar(255),
    fingerprint_pattern              varchar(150),
    tw                               varchar(100),
    place_of_temporary_residence     varchar(250),
    place_of_current_residence       varchar(250),
    date_of_arrest                   date,
    "unit_of_arrest "                varchar(250),
    incident                         varchar(500),
    finger_quality                   varchar(100),
    case_number                      varchar(30),
    face                             varchar(150),
    height                           varchar(25),
    nasal_bridge                     varchar(40),
    personal_specific_sdentification varchar(100),
    lower_ear_fold                   varchar(50),
    earlobe                          varchar(50),
    malformation                     varchar(100),
    officer_in_charge                varchar(100),
    create_time                      date,
    create_user                      integer,
    update_time                      date,
    update_user                      integer
);

alter table criminal_id_record
    owner to dev1;

